version: '3.4'

services:

  backend:
    image: 'ubersante-backend:latest'
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
        mode: host

  frontend:
    image: 'ubersante-frontend:v3'
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
