version: '3.4'

services:

  backend:
    image: 'us.gcr.io/soen341-218021/ubersante-backend:prod'
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
        mode: host

  frontend:
    image: 'us.gcr.io/soen341-218021/ubersante-frontend:prod'
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
