version: '3.4'

services:
  mongo:
    image: mongo:4.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: mongodata
        target: /data/db

  ui:
    image: mongo-express:0.49
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host

volumes:
  mongodata:
